SET NAMES utf8mb4;
UPDATE hoteles SET direccion = 'Tokio, Japón' WHERE direccion = 'Tokio, JapÃ³n';
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Sakura Plaza', 'Tokio, Japón', 5);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Neon Boutique', 'Tokio, Japón', 5);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Imperial Plaza', 'Tokio, Japón', 5);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Zen Suites', 'Tokio, Japón', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Shibuya Resort', 'Tokio, Japón', 5);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Shinjuku Plaza', 'Tokio, Japón', 4);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Fuji View Suites', 'Tokio, Japón', 4);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Edo Suites', 'Tokio, Japón', 5);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Meiji Boutique', 'Tokio, Japón', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Ginza Resort', 'Tokio, Japón', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Eiffel Suites', 'París, Francia', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Louvre Resort', 'París, Francia', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Seine Grand', 'París, Francia', 5);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Montmartre Resort', 'París, Francia', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Bastille Suites', 'París, Francia', 5);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Notre Dame Resort', 'París, Francia', 5);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Champs Plaza', 'París, Francia', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Amelie Resort', 'París, Francia', 5);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Rivoli Resort', 'París, Francia', 4);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Versailles Boutique', 'París, Francia', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Colosseum Grand', 'Roma, Italia', 4);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Vatican Resort', 'Roma, Italia', 5);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Trevi Spa', 'Roma, Italia', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Pantheon Resort', 'Roma, Italia', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Navona Spa', 'Roma, Italia', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Palatino Suites', 'Roma, Italia', 4);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Forum Grand', 'Roma, Italia', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Borghese Plaza', 'Roma, Italia', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Spanish Steps Grand', 'Roma, Italia', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Tiber Boutique', 'Roma, Italia', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Maya Grand', 'Cancún, México', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Playa Grand', 'Cancún, México', 5);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Tulum Suites', 'Cancún, México', 5);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Caribe Plaza', 'Cancún, México', 4);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Oasis Resort', 'Cancún, México', 5);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Azul Spa', 'Cancún, México', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Riviera Spa', 'Cancún, México', 4);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Palms Resort', 'Cancún, México', 5);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Sunset Plaza', 'Cancún, México', 5);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Coral Boutique', 'Cancún, México', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Thames Grand', 'Londres, Reino Unido', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Big Ben Spa', 'Londres, Reino Unido', 5);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Tower Grand', 'Londres, Reino Unido', 5);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Hyde Plaza', 'Londres, Reino Unido', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Regent Spa', 'Londres, Reino Unido', 5);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Covent Grand', 'Londres, Reino Unido', 5);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Piccadilly Boutique', 'Londres, Reino Unido', 4);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Soho Boutique', 'Londres, Reino Unido', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Victoria Suites', 'Londres, Reino Unido', 5);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Oxford Grand', 'Londres, Reino Unido', 4);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Manhattan Plaza', 'Nueva York, USA', 4);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Central Grand', 'Nueva York, USA', 5);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Times Boutique', 'Nueva York, USA', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Brooklyn Suites', 'Nueva York, USA', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Empire Resort', 'Nueva York, USA', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Liberty Suites', 'Nueva York, USA', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Broadway Spa', 'Nueva York, USA', 4);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel SoHo Resort', 'Nueva York, USA', 3);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Chelsea Spa', 'Nueva York, USA', 4);
INSERT INTO hoteles (nombre, direccion, estrellas) VALUES ('Hotel Fifth Ave Grand', 'Nueva York, USA', 5);
